[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test/forge'
solc = "0.8.13"
optimizer = true
optimizer_runs = 200

remappings = [
    "@interop/=lib/interop-lib/src/",
    "forge-std/=lib/forge-std/src/"
] 